language: generic
sudo: required

services:
    - docker
before_install:
    - docker build -t ankurbnsl8099/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true ankurbnsl8099/react-test npm run test
after_success:
    - docker build -t ankurbnsl8099/multi-client ./client
    - docker build -t ankurbnsl8099/multi-nginx ./nginx
    - docker build -t ankurbnsl8099/multi-server ./server
    - docker build -t ankurbnsl8099/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ankurbnsl8099/multi-client
    - docker push ankurbnsl8099/multi-nginx 
    - docker push ankurbnsl8099/multi-server
    - docker push ankurbnsl8099/multi-worker